language: objective-c
osx_image: xcode10
script: xcodebuild -scheme Blahker clean && xcodebuild -sdk iphonesimulator -project Blahker.xcodeproj -scheme Blahker -destination 'platform=iOS Simulator,name=iPhone X,OS=12.0' test